# -*- coding: utf-8 -*-
"""One-shot registry update for the 2026-08-29 morning Facebook scan."""
from __future__ import annotations
import json, logging, os
from datetime import datetime, timezone
import cozy_catalog

log=logging.getLogger("fb-marketplace-morning-scan-20260829")
ITEMS=[
{"source_id":"facebook_marketplace_1057893253764179","source_url":"https://www.facebook.com/marketplace/item/1057893253764179/","owner_url":"https://www.facebook.com/marketplace/profile/100007933233815/?product_id=1057893253764179","owner":"Alphaax Alphaax","price":"80000","district":"Lamai","type":"private sea-view pool villa","bedrooms":3,"bathrooms":3,"pool":"private infinity","availability":"Advertised available 2026-09-01 to 2026-12-01; owner confirmation pending","deposit":"not specified","utilities":"not specified","minimum_stay":"extended stay/long-term; exact minimum not specified","restrictions":"not specified","original_text":"Renovated 3-bedroom, 3-bathroom sea-view villa in Lamai hills with private infinity pool, furnished open-plan living and equipped kitchen. Advertised 80,000 THB/month, available 1 September to 1 December 2026."},
{"source_id":"facebook_marketplace_1560794451608669","source_url":"https://www.facebook.com/marketplace/item/1560794451608669/","owner_url":"https://www.facebook.com/marketplace/profile/100055178303074/?product_id=1560794451608669","owner":"Diana Yang","price":"46000","district":"Bophut, Soi Khao Phra","type":"townhouse/shared-pool house","bedrooms":2,"bathrooms":2.5,"pool":"shared","availability":"Advertised available; owner confirmation pending","deposit":"50,000 THB","utilities":"Internet and weekly cleaning included; electricity 8 THB/unit; water 400 THB/month","minimum_stay":"1 month; 49,000 for 1-5 months, 46,000 for 6-12 months","restrictions":"not specified","original_text":"125 sqm furnished 2-bedroom, 2.5-bathroom shared-pool townhouse in Bophut Soi Khao Phra. 49,000 THB/month for 1-5 months or 46,000 for 6-12 months. Deposit 50,000. Internet and weekly cleaning included; electricity 8/unit, water 400/month."},
{"source_id":"facebook_marketplace_1611002240700709","source_url":"https://www.facebook.com/marketplace/item/1611002240700709/","owner_url":"https://www.facebook.com/marketplace/profile/100011884336639/?product_id=1611002240700709","owner":"Praewa Promsopha","price":"85000","district":"Maenam / Ban Tai","type":"private pool villa","bedrooms":3,"bathrooms":3,"pool":"private infinity","availability":"Advertised available; owner confirmation pending","deposit":"standard deposit not specified; pets add 1 month","utilities":"Pool/garden maintenance included; water 1,500/month; internet 800/month; electricity government rate","minimum_stay":"12-month contract only","restrictions":"Small/medium dogs allowed with extra deposit","original_text":"Modern furnished 3-bedroom villa on 1,000 sqm fenced land in Maenam/Ban Tai with infinity pool and large garden. 85,000 THB/month on a 12-month contract. Pool and garden maintenance included. Water 1,500/month, internet 800/month, electricity government rate."},
{"source_id":"facebook_marketplace_1870573643905799","source_url":"https://www.facebook.com/marketplace/item/1870573643905799/","owner_url":"https://www.facebook.com/marketplace/profile/100001213605818/?product_id=1870573643905799","owner":"Pensiri Penny Panpunt","price":"95000","district":"Bangrak","type":"private pool villa","bedrooms":3,"bathrooms":3,"pool":"private","availability":"Advertised available now; owner confirmation pending","deposit":"1 month","utilities":"Weekly cleaning, internet, pool maintenance and well water included; electricity government rate; linen 500 THB/room","minimum_stay":"95,000 for 6-12 months; 120,000 December-March","restrictions":"not specified","original_text":"Three-bedroom pool villa in Bangrak. 95,000 THB/month for 6-12 months and 120,000 December-March. Weekly cleaning, internet, pool maintenance and well water included. Electricity government rate; linen change 500/room. Deposit 1 month; 50% advance required to secure."},
{"source_id":"facebook_marketplace_2381958795971461","source_url":"https://www.facebook.com/marketplace/item/2381958795971461/","owner_url":"https://www.facebook.com/marketplace/profile/100000019767873/?product_id=2381958795971461","owner":"Nina Maneerat","price":"145000","district":"Bophut","type":"private pool villa","bedrooms":3,"bathrooms":4,"pool":"private","availability":"Advertised available now; owner confirmation pending","deposit":"not specified","utilities":"Electricity and water charged separately by usage","minimum_stay":"not specified","restrictions":"not specified","original_text":"Large single-level family villa on approximately 800 sqm plot in Bophut with 3 bedrooms, 4 bathrooms, private pool, tropical garden, parking and no stairs. Marketplace card price 145,000 THB/month. Advertised ready to move in; utilities excluded."},
{"source_id":"facebook_marketplace_1591566445791252","source_url":"https://www.facebook.com/marketplace/item/1591566445791252/","owner_url":"https://www.facebook.com/marketplace/profile/100065378491465/?product_id=1591566445791252","owner":"Apilada Ketkaew","price":"120000","district":"Bophut","type":"luxury private pool villa","bedrooms":3,"bathrooms":3,"pool":"private","availability":"Advertised available now; owner confirmation pending","deposit":"not specified","utilities":"Weekly cleaning, pool/garden maintenance, monthly pest control and internet included; electricity government rate; water 40 THB/unit","minimum_stay":"minimum 1 year","restrictions":"price discrepancy: English 120,000 THB, Thai 110,000 THB; must clarify","original_text":"Luxury 3-bedroom, 3-bathroom pool villa in Bophut, 250 sqm building on 500 sqm land. English text says 120,000 THB/month; Thai text says 110,000 THB/month. Minimum one-year contract. Weekly cleaning, pool/garden care, monthly pest control and internet included."},
{"source_id":"facebook_marketplace_27932154726443674","source_url":"https://www.facebook.com/marketplace/item/27932154726443674/","owner_url":"https://www.facebook.com/marketplace/profile/100065378491465/?product_id=27932154726443674","owner":"Apilada Ketkaew","price":"250000","district":"Bangrak","type":"three-floor sea-view private pool villa","bedrooms":3,"bathrooms":5,"pool":"private","availability":"Advertised available; owner confirmation pending","deposit":"not specified","utilities":"Weekly cleaning, pool maintenance and internet included; electricity 8 THB/unit; water 1,000/month","minimum_stay":"long-term implied; exact minimum not specified","restrictions":"No pets","original_text":"Three-floor sea-view villa in Bangrak with rooftop, 3 ensuite bedrooms, 2 guest bathrooms, private pool, basement, storage, washer/dryer and EV charger support. 250,000 THB/month. Weekly cleaning, pool service and internet included; electricity 8/unit, water 1,000/month. No pets."}
]

def enabled(): return os.getenv("RECORD_FB_SCAN_20260829_MORNING","0").strip().lower() in {"1","true","yes","on"}

def _sheet(book,title,header):
    try:return book.worksheet(title)
    except Exception:
        ws=book.add_worksheet(title=title,rows=1000,cols=max(12,len(header))); ws.append_row(header,value_input_option="RAW"); return ws

def run():
    if not enabled(): return {"enabled":False}
    now=datetime.now(timezone.utc).isoformat(timespec="seconds"); book=cozy_catalog._client().open_by_key(cozy_catalog.SHEET_ID)
    src=_sheet(book,"SourceRegistry",["created_at","source_id","source_url","owner_url","original_price_thb","original_description","availability","channels_json","lots_json","message_ids_json","status","notes"])
    own=_sheet(book,"OwnersAvailability",["checked_at","source_id","owner","source_url","owner_url","availability","owner_price_thb","deposit","utilities","reservation","status","notes"])
    sr=src.get_all_values(); ora=own.get_all_values(); si={r[1]:i for i,r in enumerate(sr[1:],2) if len(r)>1}; oi={r[1]:i for i,r in enumerate(ora[1:],2) if len(r)>1}
    added=[]; updated=[]
    for x in ITEMS:
        notes=json.dumps({"district":x["district"],"type":x["type"],"bedrooms":x["bedrooms"],"bathrooms":x["bathrooms"],"pool":x["pool"],"minimum_stay":x["minimum_stay"],"restrictions":x["restrictions"],"last_checked":now,"contact_status":"not_sent_browser_confirmation_unavailable"},ensure_ascii=False)
        row=[now,x["source_id"],x["source_url"],x["owner_url"],x["price"],x["original_text"],x["availability"],"[]","{}","{}","new_needs_owner_reply",notes]
        if x["source_id"] in si: src.update(f"A{si[x['source_id']]}:L{si[x['source_id']]}",[row],value_input_option="RAW"); updated.append(x["source_id"])
        else: src.append_row(row,value_input_option="RAW"); added.append(x["source_id"])
        onotes=json.dumps({"district":x["district"],"type":x["type"],"bedrooms":x["bedrooms"],"bathrooms":x["bathrooms"],"pool":x["pool"],"restrictions":x["restrictions"],"original_listing_text":x["original_text"],"ru_summary":x["original_text"],"last_reply":None,"conversation_url":None},ensure_ascii=False)
        orow=[now,x["source_id"],x["owner"],x["source_url"],x["owner_url"],x["availability"],x["price"],x["deposit"],x["utilities"],"Advance/payment method, cancellation and booking point require owner confirmation","awaiting_contact",onotes]
        if x["source_id"] in oi: own.update(f"A{oi[x['source_id']]}:L{oi[x['source_id']]}",[orow],value_input_option="RAW")
        else: own.append_row(orow,value_input_option="RAW")
    result={"enabled":True,"added":added,"updated":updated,"count":len(ITEMS),"duplicates_excluded":["facebook_marketplace_1577360804089972"]}; log.info("RECORD_FB_SCAN_20260829_MORNING_DONE %s",json.dumps(result,ensure_ascii=False)); return result
